"""autogenerated by genpy from cv_bridge_test/Robot_Status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Robot_Status(genpy.Message):
  _md5sum = "bef20fc5bc7e72451d8bbd05d3bb647d"
  _type = "cv_bridge_test/Robot_Status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 position_x
float64 position_y
float64 position_st
float64 velocity_l
float64 velocity_r
float64 current_rst1
float64 current_rst2
float64 current_rst3
float64 current_rst4
float64 current_lst1
float64 current_lst2
float64 current_lst3
float64 current_lst4
float64 current_lpx
float64 current_lpy
float64 current_lpz
float64 current_rpx
float64 current_rpy
float64 current_rpz


"""
  __slots__ = ['position_x','position_y','position_st','velocity_l','velocity_r','current_rst1','current_rst2','current_rst3','current_rst4','current_lst1','current_lst2','current_lst3','current_lst4','current_lpx','current_lpy','current_lpz','current_rpx','current_rpy','current_rpz']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position_x,position_y,position_st,velocity_l,velocity_r,current_rst1,current_rst2,current_rst3,current_rst4,current_lst1,current_lst2,current_lst3,current_lst4,current_lpx,current_lpy,current_lpz,current_rpx,current_rpy,current_rpz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Robot_Status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position_x is None:
        self.position_x = 0.
      if self.position_y is None:
        self.position_y = 0.
      if self.position_st is None:
        self.position_st = 0.
      if self.velocity_l is None:
        self.velocity_l = 0.
      if self.velocity_r is None:
        self.velocity_r = 0.
      if self.current_rst1 is None:
        self.current_rst1 = 0.
      if self.current_rst2 is None:
        self.current_rst2 = 0.
      if self.current_rst3 is None:
        self.current_rst3 = 0.
      if self.current_rst4 is None:
        self.current_rst4 = 0.
      if self.current_lst1 is None:
        self.current_lst1 = 0.
      if self.current_lst2 is None:
        self.current_lst2 = 0.
      if self.current_lst3 is None:
        self.current_lst3 = 0.
      if self.current_lst4 is None:
        self.current_lst4 = 0.
      if self.current_lpx is None:
        self.current_lpx = 0.
      if self.current_lpy is None:
        self.current_lpy = 0.
      if self.current_lpz is None:
        self.current_lpz = 0.
      if self.current_rpx is None:
        self.current_rpx = 0.
      if self.current_rpy is None:
        self.current_rpy = 0.
      if self.current_rpz is None:
        self.current_rpz = 0.
    else:
      self.position_x = 0.
      self.position_y = 0.
      self.position_st = 0.
      self.velocity_l = 0.
      self.velocity_r = 0.
      self.current_rst1 = 0.
      self.current_rst2 = 0.
      self.current_rst3 = 0.
      self.current_rst4 = 0.
      self.current_lst1 = 0.
      self.current_lst2 = 0.
      self.current_lst3 = 0.
      self.current_lst4 = 0.
      self.current_lpx = 0.
      self.current_lpy = 0.
      self.current_lpz = 0.
      self.current_rpx = 0.
      self.current_rpy = 0.
      self.current_rpz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_19d.pack(_x.position_x, _x.position_y, _x.position_st, _x.velocity_l, _x.velocity_r, _x.current_rst1, _x.current_rst2, _x.current_rst3, _x.current_rst4, _x.current_lst1, _x.current_lst2, _x.current_lst3, _x.current_lst4, _x.current_lpx, _x.current_lpy, _x.current_lpz, _x.current_rpx, _x.current_rpy, _x.current_rpz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 152
      (_x.position_x, _x.position_y, _x.position_st, _x.velocity_l, _x.velocity_r, _x.current_rst1, _x.current_rst2, _x.current_rst3, _x.current_rst4, _x.current_lst1, _x.current_lst2, _x.current_lst3, _x.current_lst4, _x.current_lpx, _x.current_lpy, _x.current_lpz, _x.current_rpx, _x.current_rpy, _x.current_rpz,) = _struct_19d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_19d.pack(_x.position_x, _x.position_y, _x.position_st, _x.velocity_l, _x.velocity_r, _x.current_rst1, _x.current_rst2, _x.current_rst3, _x.current_rst4, _x.current_lst1, _x.current_lst2, _x.current_lst3, _x.current_lst4, _x.current_lpx, _x.current_lpy, _x.current_lpz, _x.current_rpx, _x.current_rpy, _x.current_rpz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 152
      (_x.position_x, _x.position_y, _x.position_st, _x.velocity_l, _x.velocity_r, _x.current_rst1, _x.current_rst2, _x.current_rst3, _x.current_rst4, _x.current_lst1, _x.current_lst2, _x.current_lst3, _x.current_lst4, _x.current_lpx, _x.current_lpy, _x.current_lpz, _x.current_rpx, _x.current_rpy, _x.current_rpz,) = _struct_19d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_19d = struct.Struct("<19d")
