(cl:in-package cv_bridge_test-msg)
(cl:export '(POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_ST-VAL
          POSITION_ST
          VELOCITY_L-VAL
          VELOCITY_L
          VELOCITY_R-VAL
          VELOCITY_R
          CURRENT_RST1-VAL
          CURRENT_RST1
          CURRENT_RST2-VAL
          CURRENT_RST2
          CURRENT_RST3-VAL
          CURRENT_RST3
          CURRENT_RST4-VAL
          CURRENT_RST4
          CURRENT_LST1-VAL
          CURRENT_LST1
          CURRENT_LST2-VAL
          CURRENT_LST2
          CURRENT_LST3-VAL
          CURRENT_LST3
          CURRENT_LST4-VAL
          CURRENT_LST4
          CURRENT_LPX-VAL
          CURRENT_LPX
          CURRENT_LPY-VAL
          CURRENT_LPY
          CURRENT_LPZ-VAL
          CURRENT_LPZ
          CURRENT_RPX-VAL
          CURRENT_RPX
          CURRENT_RPY-VAL
          CURRENT_RPY
          CURRENT_RPZ-VAL
          CURRENT_RPZ
))