(cl:in-package cv_bridge_test-msg)
(cl:export '(CMD_ID-VAL
          CMD_ID
          CMD_FLAG-VAL
          CMD_FLAG
          HAND_NUM-VAL
          HAND_NUM
          JOINT_NUM-VAL
          JOINT_NUM
          TARGET_RST1-VAL
          TARGET_RST1
          TARGET_RST2-VAL
          TARGET_RST2
          TARGET_RST3-VAL
          TARGET_RST3
          TARGET_RST4-VAL
          TARGET_RST4
          TARGET_LST1-VAL
          TARGET_LST1
          TARGET_LST2-VAL
          TARGET_LST2
          TARGET_LST3-VAL
          TARGET_LST3
          TARGET_LST4-VAL
          TARGET_LST4
          TARGET_POSITIONX-VAL
          TARGET_POSITIONX
          TARGET_POSITIONY-VAL
          TARGET_POSITIONY
          TARGET_POSITIONST-VAL
          TARGET_POSITIONST
))